sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    sprite.setImage(assets.image`Grunt`)
    info.setLife(3)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ..........c.....................
        ..........ccccccccc.............
        ........cccddddddd..............
        ..........ccccccc...............
        ..........c.....................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, ninja, 50, 0)
    pause(1000)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    ninja.vy = -50
})
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.forestTiles6, function (sprite, location) {
    sprite.say("Stop cheating ;).", 1000)
    sprite.vy = 50
    pause(200)
    info.changeLifeBy(-1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    game.over(false)
})
info.onLifeZero(function () {
    game.over(false)
})
info.player2.onLifeZero(function () {
    grunt.destroy(effects.fire, 500)
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.rock2, function (sprite, location) {
    if (info.player1.score() == 20) {
        tiles.setTilemap(tilemap`level2`)
        tiles.placeOnTile(ninja, tiles.getTileLocation(1, 6))
    } else {
        game.splash("Clear the enemies first.")
        pause(700)
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(10)
    info.player2.changeLifeBy(-1)
    pause(900)
})
let projectile: Sprite = null
let grunt: Sprite = null
let ninja: Sprite = null
tiles.setTilemap(tilemap`level1`)
ninja = sprites.create(assets.image`Ninja`, SpriteKind.Player)
controller.moveSprite(ninja, 100, 0)
ninja.ay = 250
tiles.placeOnTile(ninja, tiles.getTileLocation(1, 6))
scene.cameraFollowSprite(ninja)
grunt = sprites.create(assets.image`Grunt`, SpriteKind.Enemy)
tiles.placeOnTile(grunt, tiles.getTileLocation(17, 6))
grunt.setBounceOnWall(true)
grunt.ay = 50
grunt.vx = -25
info.setLife(5)
info.player2.setLife(2)
